### ISSUE TITLE
Race condition between connection being closed, and writing to socket hangs forever

### ISSUE THREAD

**Issue by mattrobenolt** [JanBerktold/sse#2]
https://github.com/JanBerktold/sse/blob/master/conn.go#L28-L36

If `conn.isOpen` is true, it's possible to try to write to the socket here: https://github.com/JanBerktold/sse/blob/master/upgrade.go#L59-L60

And hang forever.

At least this is what it's seeming like since it blocks on putting the message into the messages channel, blocking a `WriteEvent()` call.

**Comment by JanBerktold** [comment]
First of all, thanks for the input! 

That should be fixable by closing the messages channel on shutdown of the connection.

Perhaps the shutdown channel could also be made obsolete.. 

I will take care of this ASAP.

**Comment by clbanning** [comment]
Fix for potential race condition is contributed in pull request.

**Comment by clbanning** [comment]
Closing the messages channel is only safe if the conn is held by a single go routine that is also closed - otherwise you'll get a panic for writing on a closed channel. (http://localhost:6060/ref/spec#Close)

For my own use, I patched this in https://github.com/clbanning/sse using the conn.IsOpen().

**Comment by nvartolomei** [comment]
Looks like this should be closed now. 👻
